# Generated by Django 4.2 on 2024-01-08 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4cf45c67-7968-49a4-adc2-32dd2475e56e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
