# Generated by Django 4.2 on 2024-01-08 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.UUID('dc518abf-16e0-4fb6-b805-885211eaccde'), editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb3b195c-c9d8-4acd-963c-520f2889c5a4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
