# Generated by Django 4.2 on 2024-01-08 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tags_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='projects.tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('925b5224-6b7d-4fa2-a750-bc9b1aabdf3a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76489747-d9a1-40de-ba97-32658cf1b9e5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
