# Generated by Django 4.2 on 2024-01-10 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
        ('projects', '0005_project_owner_alter_project_id_alter_tags_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('text', models.TextField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike')], max_length=200, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
