# Generated by Django 4.2 on 2024-01-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='static/images/projects-images/default-image.jpg', null=True, upload_to='project-images/'),
        ),
    ]
